language: php

php:
  - 7.1

before_script:
  - phpenv config-rm xdebug.ini
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan migrate

before_install:
  - bash .travis.install-mysql-5.7.sh
  - mysql -e 'CREATE DATABASE test;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

services:
  - mysql

sudo: true

cache:
  directories:
    - vendor
